# This is AI made. It converts an image to a raw c array to be embedded directly.

#!/usr/bin/env python3
# png_to_carray.py
from PIL import Image
import sys
import os

def usage():
    print("Usage: png_to_carray.py input.png output.h [varname] [width] [height]")
    sys.exit(1)

if len(sys.argv) < 3:
    usage()

inp = sys.argv[1]
out = sys.argv[2]
varname = sys.argv[3] if len(sys.argv) >= 4 else "image"
forced_w = int(sys.argv[4]) if len(sys.argv) >= 5 else None
forced_h = int(sys.argv[5]) if len(sys.argv) >= 6 else None

im = Image.open(inp).convert("RGBA")
w, h = im.size
if forced_w and forced_h:
    if forced_w != w or forced_h != h:
        print(f"Warning: forced size {forced_w}x{forced_h} differs from image {w}x{h}. Using actual PNG size {w}x{h}.")
data = im.tobytes()  # RGBA order

with open(out, "w") as f:
    f.write("// generated by png_to_carray.py\n")
    f.write(f"#define IMAGE_W {w}\n")
    f.write(f"#define IMAGE_H {h}\n\n")
    f.write(f"static const unsigned char {varname}[] = {{\n")
    for i, b in enumerate(data):
        if i % 12 == 0:
            f.write("    ")
        f.write("0x%02X, " % b)
        if i % 12 == 11:
            f.write("\n")
    if len(data) % 12 != 0:
        f.write("\n")
    f.write("};\n")
    f.write(f"static const unsigned int {varname}_len = {len(data)};\n")

print(f"Wrote {out} ({w}x{h}, {len(data)} bytes)")
