#!/usr/bin/env python3
"""AI BUILT. Convert fixed-size RGBA PNGs into a C header of PSP 5551 pixels."""

import argparse
import re
from pathlib import Path

from PIL import Image


def symbol_for(path):
	name = re.sub(r"[^a-zA-Z0-9_]", "_", path.stem)
	if not name or name[0].isdigit():
		name = "image_" + name
	return name


def convert(path, image_size, alpha_threshold):
	image = Image.open(path).convert("RGBA")
	if image.size != (image_size, image_size):
		raise ValueError(
			f"{path}: expected {image_size}x{image_size}, got {image.width}x{image.height}"
		)

	pixels = []
	for red, green, blue, alpha in image.getdata():
		pixel = (red >> 3) | ((green >> 3) << 5) | ((blue >> 3) << 10)
		if alpha >= alpha_threshold:
			pixel |= 0x8000
		pixels.append(f"0x{pixel:04X}")
	return symbol_for(path), pixels


def main():
	parser = argparse.ArgumentParser()
	parser.add_argument("output", type=Path)
	parser.add_argument("inputs", nargs="*", type=Path)
	parser.add_argument("--size", type=int, default=32)
	parser.add_argument("--alpha-threshold", type=int, default=128)
	args = parser.parse_args()

	if not 0 <= args.alpha_threshold <= 255:
		parser.error("--alpha-threshold must be between 0 and 255")

	assets = [convert(path, args.size, args.alpha_threshold) for path in args.inputs]
	lines = [
		"/* Generated by tools/png_to_5551.py. Do not edit. */",
		"#ifndef BT_CTR_OVERLAY_IMAGE_ASSETS_H",
		"#define BT_CTR_OVERLAY_IMAGE_ASSETS_H",
		"",
	]

	for symbol, pixels in assets:
		lines.append(f"static const u16 {symbol}_pixels[] = {{")
		for offset in range(0, len(pixels), 8):
			lines.append("\t" + ", ".join(pixels[offset:offset + 8]) + ",")
		lines.extend([
			"};",
			f"static const BitmapImage {symbol} = {{{symbol}_pixels, {args.size}, {args.size}}};",
			"",
		])

	lines.append("#endif")
	args.output.parent.mkdir(parents=True, exist_ok=True)
	args.output.write_text("\n".join(lines) + "\n", encoding="ascii")


if __name__ == "__main__":
	main()