name: C/C++ CI

on:
  push:
    branches: [ develop ]
    tags: '**' # Trigger on tags for releases
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add build-base git bash cmake gcompat

    - name: Make Release Folder
      run: mkdir -p release
    
    - name: Compile Overlay
      run: cd overlay && ./compile.sh

    - name: Compile Plugin
      run: cd plugin && make

    - name: Prepare artifact folder
      run: |
        mkdir -p PSPBluetoothPlugin
        cp release/bt_ctr_driver.prx PSPBluetoothPlugin/
        cp release/bt_ctr_overlay.prx PSPBluetoothPlugin/

    - uses: actions/upload-artifact@v4
      with:
        name: PSPBluetoothPlugin
        path: PSPBluetoothPlugin/

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r PSPBluetoothPlugin.zip PSPBluetoothPlugin

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        prerelease: true
        files: PSPBluetoothPlugin.zip
